export const GameActionTypes = {
    SET_QUESTIONS: "SET_QUESTIONS",
    SET_PLAYER_ONE_NAME: "SET_PLAYER_ONE_NAME",
    SET_PLAYER_TWO_NAME: "SET_PLAYER_TWO_NAME",
    SET_PLAYER_ONE_SCORE: "SET_PLAYER_ONE_SCORE",
    SET_PLAYER_TWO_SCORE: "SET_PLAYER_TWO_SCORE",
    SET_MULTIPLAYER: "SET_MULTIPLAYER",
    SET_NUMBER_OF_QUESTIONS: "SET_NUMBER_OF_QUESTIONS",
    SET_CHOSEN_CATEGORY: "SET_CHOSEN_CATEGORY",
    RESET_GAME: "RESET_GAME"
} as const;